# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary_in_walkthrough: true
  pre_merge_checks:
    docstrings:
      mode: error
    title:
      mode: error
    description:
      mode: error
    issue_assessment:
      mode: error
