"""XGBoost grade estimator training for bouldering routes.

Trains an ordinal multi-class :class:`~xgboost.XGBClassifier` to predict
V-scale grades (V0–V17) from :class:`~src.features.assembler.RouteFeatures`.

Typical workflow::

    from src.training.train_grade_estimator import (
        generate_synthetic_training_data,
        train_grade_estimator,
    )

    samples = generate_synthetic_training_data(n_samples=2000, seed=42)
    features, labels = zip(*samples)
    result = train_grade_estimator(list(features), list(labels), Path("models/grading"))
    print(result.version, result.metrics.val_accuracy)

The trained model is saved to ``output_dir/<version>/`` containing:

* ``model.pkl`` — serialised ``XGBClassifier`` (via :mod:`joblib`)
* ``metadata.json`` — training provenance, normalization stats, and metrics

The model can then be used via :func:`~src.grading.ml_estimator.estimate_grade_ml`.
"""

from __future__ import annotations

import json
import math
import random
import shutil
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Literal

import joblib
import numpy as np
from pydantic import BaseModel, Field
from xgboost import XGBClassifier

from src.features.assembler import RouteFeatures, assemble_features
from src.graph.constraints import apply_route_constraints
from src.graph.route_graph import build_route_graph
from src.graph.types import ClassifiedHold
from src.grading._utils import _normalize_vector
from src.grading.constants import V_GRADES
from src.grading.exceptions import GradeEstimationError
from src.grading.heuristic import estimate_grade_heuristic
from src.logging_config import get_logger
from src.training.classification_dataset import HOLD_CLASSES

logger = get_logger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_N_GRADES = len(V_GRADES)  # 18
_MIN_TRAINING_SAMPLES = 10

# Fixed 3×4 spatial grid for synthetic route generation.
# Spacing: 0.25 (horizontal), 0.20 (vertical).
# Diagonal distance ≈ 0.32 < BASE_REACH_RADIUS (0.35) → edges always form.
_GRID_POSITIONS: list[tuple[float, float]] = [
    (x, y) for y in (0.20, 0.40, 0.60, 0.80) for x in (0.25, 0.50, 0.75)
]  # 12 positions total

# ---------------------------------------------------------------------------
# Result models
# ---------------------------------------------------------------------------


class GradeTrainingMetrics(BaseModel):
    """Metrics produced during grade estimator training.

    Attributes:
        train_accuracy: Accuracy on the training split, in ``[0, 1]``.
        val_accuracy: Accuracy on the validation split, in ``[0, 1]``.
        mean_absolute_error: Mean absolute error in grade indices on the
            validation split (ordinal-aware metric).
    """

    train_accuracy: float = Field(ge=0.0, le=1.0)
    val_accuracy: float = Field(ge=0.0, le=1.0)
    mean_absolute_error: float = Field(ge=0.0)


class GradeTrainingResult(BaseModel):
    """Result of a grade estimator training run.

    Attributes:
        version: Version string in ``v<YYYYMMDD_HHMMSS>`` format.
        model_path: Absolute path to the saved ``model.pkl``.
        metadata_path: Absolute path to the saved ``metadata.json``.
        metrics: Training and validation metrics.
        n_samples: Total number of training samples used.
        feature_names: Ordered list of feature names (34 entries).
        data_source: ``"synthetic"`` if labels were generated by the
            heuristic estimator; ``"real"`` if from a labelled dataset.
        git_commit: Short git commit hash at training time, or ``None``
            if not available.
        trained_at: ISO-8601 UTC timestamp of training completion.
        hyperparameters: XGBoost hyperparameters used for training.
    """

    version: str
    model_path: Path
    metadata_path: Path
    metrics: GradeTrainingMetrics
    n_samples: int = Field(ge=1)
    feature_names: list[str]
    data_source: Literal["synthetic", "real"]
    git_commit: str | None
    trained_at: str
    hyperparameters: dict[str, Any]


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------


def _generate_version() -> str:
    """Generate a UTC-timestamp version string.

    Returns:
        Version string in ``v<YYYYMMDD_HHMMSS>`` format.

    Example::

        >>> v = _generate_version()
        >>> assert v.startswith("v") and len(v) == 16
    """
    return datetime.now(tz=timezone.utc).strftime("v%Y%m%d_%H%M%S")


def _get_git_commit_hash() -> str | None:
    """Return the short git commit hash of HEAD, or None on failure.

    Returns:
        7-character hex string or ``None`` if git is unavailable.

    Example::

        >>> h = _get_git_commit_hash()
        >>> assert h is None or len(h) == 7
    """
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=True,
            timeout=5,
        )
        return result.stdout.strip()
    except Exception:  # noqa: BLE001  # pylint: disable=broad-exception-caught
        return None


def _compute_normalization_stats(
    vectors: list[dict[str, float]],
) -> tuple[dict[str, float], dict[str, float]]:
    """Compute per-feature mean and standard deviation from a list of vectors.

    Zero-variance features receive ``std = 0.0`` in the output (the
    :func:`~src.grading._utils._normalize_vector` function applies a
    ``std = 1.0`` fallback at inference time).

    Args:
        vectors: Non-empty list of feature dicts, all sharing the same keys.

    Returns:
        Tuple of ``(mean_dict, std_dict)`` keyed by feature name.

    Example::

        >>> mean, std = _compute_normalization_stats([{"x": 1.0}, {"x": 3.0}])
        >>> mean["x"]
        2.0
        >>> std["x"]
        1.0
    """
    n = len(vectors)
    keys = list(vectors[0].keys())
    mean: dict[str, float] = {}
    std: dict[str, float] = {}
    for k in keys:
        values = [v[k] for v in vectors]
        mu = math.fsum(values) / n
        # Population variance (÷N, not ÷N-1). Intentional: the same stats are
        # applied at both training and inference time, so the choice of N vs N-1
        # only affects the scale of normalised values, not model correctness.
        variance = math.fsum((val - mu) ** 2 for val in values) / n
        mean[k] = mu
        std[k] = math.sqrt(variance)
    return mean, std


def _make_synthetic_hold(
    hold_id: int,
    x: float,
    y: float,
    rng: random.Random,
) -> ClassifiedHold:
    """Create a ClassifiedHold at position (x, y) with randomised type.

    Args:
        hold_id: Non-negative hold identifier.
        x: Normalised x-center [0, 1].
        y: Normalised y-center [0, 1].
        rng: Seeded random instance for reproducibility.

    Returns:
        A validated :class:`~src.graph.types.ClassifiedHold`.
    """
    hold_type = rng.choice(HOLD_CLASSES)
    type_confidence = rng.uniform(0.5, 0.99)
    remaining = 1.0 - type_confidence
    other_n = len(HOLD_CLASSES) - 1
    type_probabilities = {
        c: type_confidence if c == hold_type else remaining / other_n
        for c in HOLD_CLASSES
    }
    width = rng.uniform(0.04, 0.12)
    height = rng.uniform(0.04, 0.12)
    return ClassifiedHold(
        hold_id=hold_id,
        x_center=x,
        y_center=y,
        width=width,
        height=height,
        detection_class="hold",
        detection_confidence=rng.uniform(0.6, 0.99),
        hold_type=hold_type,
        type_confidence=type_confidence,
        type_probabilities=type_probabilities,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_synthetic_training_data(
    n_samples: int = 1000,
    seed: int = 42,
) -> list[tuple[RouteFeatures, int]]:
    """Generate synthetic (RouteFeatures, grade_index) pairs for training.

    Builds routes from a fixed 3×4 spatial grid of holds (positions chosen
    to guarantee graph connectivity within ``BASE_REACH_RADIUS = 0.35``).
    Hold types and confidence values are randomised.  Grade labels are
    assigned by :func:`~src.grading.heuristic.estimate_grade_heuristic`.

    NOTE: Labels are derived from the heuristic estimator — the trained ML
    model cannot exceed heuristic accuracy on synthetic data.  Replace with
    real-world labelled data when available (set ``data_source="real"`` in
    :func:`train_grade_estimator`).

    Args:
        n_samples: Number of synthetic route samples to generate.
        seed: Random seed for reproducibility.

    Returns:
        List of ``(RouteFeatures, grade_index)`` tuples, length == *n_samples*.

    Example::

        >>> samples = generate_synthetic_training_data(n_samples=100, seed=0)
        >>> len(samples)
        100
        >>> features, label = samples[0]
        >>> 0 <= label <= 17
        True
    """
    rng = random.Random(seed)
    results: list[tuple[RouteFeatures, int]] = []

    for sample_idx in range(n_samples):
        # Use all 12 grid positions in fixed spatial order — guarantees
        # graph connectivity (all adjacent pairs are within BASE_REACH_RADIUS).
        # Variety comes from randomised hold types and confidence values.
        holds = [
            _make_synthetic_hold(i, x, y, rng)
            for i, (x, y) in enumerate(_GRID_POSITIONS)
        ]

        # Build constrained graph — full ordered grid is always connected.
        # start_id=0 (bottom-left), finish_id=11 (top-right).
        rg = build_route_graph(holds, wall_angle=rng.uniform(-10.0, 45.0))
        start_id = 0
        finish_id = len(_GRID_POSITIONS) - 1
        constrained = apply_route_constraints(rg, [start_id], finish_id)

        route_features = assemble_features(constrained)
        heuristic_result = estimate_grade_heuristic(route_features)
        results.append((route_features, heuristic_result.grade_index))

        if (sample_idx + 1) % 100 == 0:
            logger.debug(
                "Generated %d / %d synthetic samples", sample_idx + 1, n_samples
            )

    return results


def _fit_xgboost(
    features_array: "np.ndarray[Any, Any]",
    labels_array: "np.ndarray[Any, Any]",
) -> "tuple[dict[str, Any], XGBClassifier, GradeTrainingMetrics]":
    """Fit an XGBClassifier and compute train/val metrics.

    Splits *features_array* / *labels_array* 80/20, fits the classifier,
    and returns the hyperparameters dict, fitted classifier, and metrics.

    Args:
        features_array: Float32 array of shape (n_samples, n_features).
        labels_array: Int32 array of shape (n_samples,) with contiguous
            labels starting at 0.

    Returns:
        Tuple of ``(hyperparameters, fitted_classifier, metrics)``.
    """
    n_samples = len(features_array)
    n_val = max(1, int(n_samples * 0.2))
    n_train = n_samples - n_val

    rng = np.random.default_rng(seed=42)
    indices = rng.permutation(n_samples)
    train_idx, val_idx = indices[:n_train], indices[n_train:]

    train_features = features_array[train_idx]
    train_labels = labels_array[train_idx]
    val_features = features_array[val_idx]
    val_labels = labels_array[val_idx]

    hyperparameters: dict[str, Any] = {
        "objective": "multi:softprob",
        "n_estimators": 200,
        "max_depth": 4,
        "learning_rate": 0.1,
        "subsample": 0.8,
        "colsample_bytree": 0.8,
        "seed": 42,
        "eval_metric": "mlogloss",
        "early_stopping_rounds": 20,
    }

    clf = XGBClassifier(
        objective=hyperparameters["objective"],
        n_estimators=hyperparameters["n_estimators"],
        max_depth=hyperparameters["max_depth"],
        learning_rate=hyperparameters["learning_rate"],
        subsample=hyperparameters["subsample"],
        colsample_bytree=hyperparameters["colsample_bytree"],
        seed=hyperparameters["seed"],
        eval_metric=hyperparameters["eval_metric"],
        early_stopping_rounds=hyperparameters["early_stopping_rounds"],
        verbosity=0,
    )
    clf.fit(
        train_features,
        train_labels,
        eval_set=[(val_features, val_labels)],
        verbose=False,
    )

    train_preds = clf.predict(train_features)
    val_preds = clf.predict(val_features)

    train_accuracy = float(np.mean(train_preds == train_labels))
    val_accuracy = float(np.mean(val_preds == val_labels))
    mae = float(np.mean(np.abs(val_preds.astype(float) - val_labels.astype(float))))

    metrics = GradeTrainingMetrics(
        train_accuracy=train_accuracy,
        val_accuracy=val_accuracy,
        mean_absolute_error=mae,
    )
    return hyperparameters, clf, metrics


def train_grade_estimator(
    features: list[RouteFeatures],
    labels: list[int],
    output_dir: Path,
    data_source: Literal["synthetic", "real"] = "synthetic",
) -> GradeTrainingResult:
    """Train an XGBoost grade estimator and save the versioned model.

    Validates inputs, computes z-score normalisation statistics, trains an
    :class:`~xgboost.XGBClassifier` with an 80/20 train/val split, and writes
    ``model.pkl`` + ``metadata.json`` atomically to a versioned subdirectory
    of *output_dir*.

    Args:
        features: Non-empty list of :class:`~src.features.assembler.RouteFeatures`
            instances — one per training sample.
        labels: Corresponding grade indices in ``[0, 17]``, same length as
            *features*.
        output_dir: Parent directory under which the versioned model
            subdirectory is created (e.g. ``Path("models/grading")``).
        data_source: ``"synthetic"`` if labels come from
            :func:`generate_synthetic_training_data`; ``"real"`` otherwise.

    Returns:
        :class:`GradeTrainingResult` with paths, metrics, and metadata.

    Raises:
        GradeEstimationError: If inputs are invalid (length mismatch,
            too few samples, fewer than 2 unique classes, or out-of-range
            labels).

    Example::

        >>> samples = generate_synthetic_training_data(200, seed=0)
        >>> feats, lbls = zip(*samples)
        >>> result = train_grade_estimator(list(feats), list(lbls), Path("models/grading"))
        >>> result.metrics.val_accuracy > 0.0
        True
    """
    # ------------------------------------------------------------------
    # Input validation
    # ------------------------------------------------------------------
    if len(features) != len(labels):
        raise GradeEstimationError(
            f"features and labels must have the same length, "
            f"got {len(features)} features and {len(labels)} labels"
        )
    if len(features) < _MIN_TRAINING_SAMPLES:
        raise GradeEstimationError(
            f"At least {_MIN_TRAINING_SAMPLES} training samples required, "
            f"got {len(features)}"
        )
    unique_classes = set(labels)
    if len(unique_classes) < 2:
        raise GradeEstimationError(
            f"Training data must contain at least 2 unique grade classes, "
            f"got {len(unique_classes)}: {unique_classes}"
        )
    bad_labels = [lbl for lbl in labels if lbl < 0 or lbl > 17]
    if bad_labels:
        raise GradeEstimationError(
            f"All labels must be in [0, 17]; found out-of-range values: "
            f"{sorted(set(bad_labels))}"
        )

    logger.info(
        "Starting grade estimator training: n_samples=%d, data_source=%s",
        len(features),
        data_source,
    )

    # ------------------------------------------------------------------
    # Extract and normalise feature vectors
    # ------------------------------------------------------------------
    vectors = [f.to_vector() for f in features]
    feature_names = list(vectors[0].keys())
    norm_mean, norm_std = _compute_normalization_stats(vectors)
    normalised = [_normalize_vector(v, norm_mean, norm_std) for v in vectors]

    features_array = np.array(
        [[v[k] for k in feature_names] for v in normalised], dtype=np.float32
    )

    # XGBClassifier (multi:softprob) requires labels in [0, n_unique_classes - 1].
    # Remap grade indices to a contiguous local range; store the mapping in metadata
    # so estimate_grade_ml can translate local predictions back to V-grade indices.
    sorted_classes: list[int] = sorted(unique_classes)
    label_to_local: dict[int, int] = {c: i for i, c in enumerate(sorted_classes)}
    labels_array = np.array([label_to_local[lbl] for lbl in labels], dtype=np.int32)

    hyperparameters, clf, metrics = _fit_xgboost(features_array, labels_array)
    logger.info(
        "Training complete: train_acc=%.4f val_acc=%.4f mae=%.4f",
        metrics.train_accuracy,
        metrics.val_accuracy,
        metrics.mean_absolute_error,
    )

    # ------------------------------------------------------------------
    # Atomic write: temp dir → final versioned directory
    # ------------------------------------------------------------------
    version = _generate_version()
    trained_at = datetime.now(tz=timezone.utc).isoformat()
    git_commit = _get_git_commit_hash()

    # sorted_classes maps local index → V-grade index (e.g. [1,2,3,4] means
    # local class 0 → V1, local class 1 → V2, etc.).
    # Stored in metadata so estimate_grade_ml can translate predictions to V-grades.
    trained_classes: list[int] = sorted_classes

    metadata: dict[str, Any] = {
        "version": version,
        "trained_at": trained_at,
        "n_samples": len(features),
        "feature_names": feature_names,
        "n_features": len(feature_names),
        "normalization_mean": norm_mean,
        "normalization_std": norm_std,
        "n_classes": _N_GRADES,
        "classes": trained_classes,
        "data_source": data_source,
        "hyperparameters": hyperparameters,
        "git_commit": git_commit,
        "metrics": {
            "train_accuracy": metrics.train_accuracy,
            "val_accuracy": metrics.val_accuracy,
            "mean_absolute_error": metrics.mean_absolute_error,
        },
    }

    output_dir.mkdir(parents=True, exist_ok=True)
    final_dir = output_dir / version

    with tempfile.TemporaryDirectory(dir=output_dir) as tmp_str:
        tmp_dir = Path(tmp_str)
        tmp_model = tmp_dir / "model.pkl"
        tmp_metadata = tmp_dir / "metadata.json"

        joblib.dump(clf, tmp_model)
        with tmp_metadata.open("w", encoding="utf-8") as fh:
            json.dump(metadata, fh, indent=2)

        # Move temp dir to final location. shutil.move is atomic on POSIX
        # (same filesystem); on Windows it is best-effort. If interrupted,
        # the worst case is a partially-written temp dir that is cleaned up
        # by TemporaryDirectory's own context manager on process exit.
        shutil.move(str(tmp_dir), str(final_dir))

    model_path = (final_dir / "model.pkl").resolve()
    metadata_path = (final_dir / "metadata.json").resolve()

    logger.info("Model saved to %s", final_dir)

    return GradeTrainingResult(
        version=version,
        model_path=model_path,
        metadata_path=metadata_path,
        metrics=metrics,
        n_samples=len(features),
        feature_names=feature_names,
        data_source=data_source,
        git_commit=git_commit,
        trained_at=trained_at,
        hyperparameters=hyperparameters,
    )
